// Unlicense — cochranblock.org
// Contributors: GotEmCoach, KOVA, Claude Opus 4.6
// Generated by: kova micro run f80 (structure), human-corrected API calls
//! pipe — Full micro-model pipeline: classify → route → run → validate.
//! One command, end-to-end. The micro equivalent of `kova factory`.

use std::time::{Duration, Instant};

use super::registry::MicroRegistry;
use super::router::{category_to_template, classify_keywords};
use super::runner::{run_micro, Budget, CircuitBreaker};
use super::validate::{validate, ValidationResult};
use crate::cluster::Cluster;

/// Full pipeline result.
#[derive(Debug)]
pub struct PipeResult {
    /// What the classifier said.
    pub classification: String,
    /// Which template was selected.
    pub template_id: String,
    /// Template human name.
    pub template_name: String,
    /// Raw model response.
    pub response: String,
    /// Validation verdict.
    pub validation: ValidationResult,
    /// Node that handled the main run.
    pub node_id: String,
    /// Time for classification step.
    pub classify_duration: Duration,
    /// Time for main run step.
    pub run_duration: Duration,
    /// Total wall time.
    pub total_duration: Duration,
}

/// Run the full pipeline: classify → route → run → validate.
pub fn run_pipe(
    input: &str,
    registry: &MicroRegistry,
    cluster: &Cluster,
) -> Result<PipeResult, String> {
    let total_start = Instant::now();
    let breaker = CircuitBreaker::new(3);
    let budget = Budget::new(100_000);

    // Step 1: Classify via f79 (or keyword fallback if no nodes)
    let classify_start = Instant::now();
    let classification = match registry.get("f79") {
        Some(tmpl) => {
            match run_micro(tmpl, input, cluster, &breaker, &budget) {
                Ok(result) => result.response.trim().to_lowercase(),
                Err(_) => {
                    // Fallback to keyword classification
                    classify_keywords(input)
                }
            }
        }
        None => classify_keywords(input),
    };
    let classify_duration = classify_start.elapsed();

    // Step 2: Map classification to template
    let template_id = category_to_template(&classification);
    let tmpl = registry
        .get(&template_id)
        .ok_or_else(|| format!("no template for category: {}", classification))?;

    // Step 3: Run the template
    let run_start = Instant::now();
    let result = run_micro(tmpl, input, cluster, &breaker, &budget)?;
    let run_duration = run_start.elapsed();

    // Step 4: Validate
    let validation = validate(&result, input, &tmpl.output_schema);

    let total_duration = total_start.elapsed();

    Ok(PipeResult {
        classification,
        template_id,
        template_name: tmpl.name.clone(),
        response: result.response,
        validation,
        node_id: result.node_id,
        classify_duration,
        run_duration,
        total_duration,
    })
}

/// Print a pipe result in human-readable format.
pub fn print_pipe_result(r: &PipeResult) {
    println!("{}", r.response);
    eprintln!("──────────────────────────────────────────");
    eprintln!(
        "[pipe] classify: {} → {} ({})",
        r.classification, r.template_id, r.template_name
    );
    eprintln!("[pipe] node: {}", r.node_id);
    eprintln!(
        "[pipe] timing: classify {:.1}s, run {:.1}s, total {:.1}s",
        r.classify_duration.as_secs_f64(),
        r.run_duration.as_secs_f64(),
        r.total_duration.as_secs_f64()
    );
    eprintln!(
        "[pipe] validation: {} (confidence: {:.0}%)",
        r.validation.summary,
        r.validation.confidence * 100.0
    );
}
